site_name: BIT-IUSEPN-Lab


nav:
- 研究方向: ResearchDirection.md

- 平台建设: PlatformConstruction.md

- 最新成果: LatestResults.md

- 资源公开: ResourceDisclosure.md

- BIT航行器俱乐部: BITUnmannedVehicleClub.md

theme:
  name: 'material'
  
extra_css:
  - css/custom.css
